#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Toggle Monocle
# @raycast.mode silent
# @raycast.refreshTime disabled

# Optional parameters:
# @raycast.icon ../icons/monocle.png
# Documentation:
# @raycast.description Turn Monocle on and off
# @raycast.author Manik

active_app=$(osascript -e 'tell application "System Events" to get name of first application process whose frontmost is true')

open monocle://toggle

osascript -e "tell application \"$active_app\" to activate"

